"""Mock South Australian tender data — fallback when APIs are down."""

MOCK_TENDERS = [
    {
        "external_id": "SA-2025-001",
        "title": "Supply and Installation of Solar PV Systems for Government Buildings",
        "description": "Tender for the design, supply, installation and maintenance of rooftop solar photovoltaic systems across multiple government-owned buildings in metropolitan Adelaide.",
        "agency": "Department for Infrastructure and Transport",
        "status": "open",
        "value_amount": 2450000.00,
        "value_currency": "AUD",
        "published_date": "2025-05-01",
        "closing_date": "2025-06-15",
        "location": "South Australia",
        "category": "Energy / Infrastructure",
        "source": "mock",
        "url": "https://www.tenders.sa.gov.au/tender/SA-2025-001"
    },
    {
        "external_id": "SA-2025-002",
        "title": "Virtual Power Plant (VPP) Aggregation Platform — Phase 2",
        "description": "Seeking a technology partner to operate a cloud-based VPP aggregation platform integrating residential battery storage and EV chargers for grid services.",
        "agency": "Office of the Industry Advocate",
        "status": "open",
        "value_amount": 1800000.00,
        "value_currency": "AUD",
        "published_date": "2025-04-20",
        "closing_date": "2025-06-01",
        "location": "South Australia",
        "category": "Clean Tech / VPP",
        "source": "mock",
        "url": "https://www.tenders.sa.gov.au/tender/SA-2025-002"
    },
    {
        "external_id": "SA-2025-003",
        "title": "Provision of Demand Response Services for Summer Peak Events",
        "description": "Procurement of demand response capacity to manage summer peak electricity demand events. Open to commercial and industrial load aggregators.",
        "agency": "SA Power Networks",
        "status": "open",
        "value_amount": 3200000.00,
        "value_currency": "AUD",
        "published_date": "2025-05-05",
        "closing_date": "2025-07-10",
        "location": "South Australia",
        "category": "Energy / Demand Response",
        "source": "mock",
        "url": "https://www.tenders.sa.gov.au/tender/SA-2025-003"
    },
    {
        "external_id": "SA-2025-004",
        "title": "IoT Sensor Network for Smart Street Lighting Upgrade",
        "description": "Deployment of LoRaWAN-enabled IoT sensors for adaptive street lighting control, fault detection and energy monitoring across regional SA.",
        "agency": "Local Government Association of SA",
        "status": "open",
        "value_amount": 890000.00,
        "value_currency": "AUD",
        "published_date": "2025-04-28",
        "closing_date": "2025-06-20",
        "location": "South Australia",
        "category": "IoT / Smart Cities",
        "source": "mock",
        "url": "https://www.tenders.sa.gov.au/tender/SA-2025-004"
    },
    {
        "external_id": "SA-2025-005",
        "title": "Electric Vehicle Charging Infrastructure — Regional Hubs",
        "description": "Design, build and operate DC fast-charging stations at key regional transport hubs including Port Augusta, Mount Gambier and Murray Bridge.",
        "agency": "Department for Energy and Mining",
        "status": "open",
        "value_amount": 5600000.00,
        "value_currency": "AUD",
        "published_date": "2025-05-10",
        "closing_date": "2025-08-01",
        "location": "South Australia",
        "category": "EV Infrastructure",
        "source": "mock",
        "url": "https://www.tenders.sa.gov.au/tender/SA-2025-005"
    },
    {
        "external_id": "SA-2025-006",
        "title": "Cybersecurity Audit and Hardening — Critical Infrastructure",
        "description": "Comprehensive cybersecurity assessment, penetration testing and remediation for SCADA and operational technology systems in water and energy utilities.",
        "agency": "Essential Services Commission of SA",
        "status": "closed",
        "value_amount": 450000.00,
        "value_currency": "AUD",
        "published_date": "2025-02-15",
        "closing_date": "2025-03-30",
        "location": "South Australia",
        "category": "Cybersecurity",
        "source": "mock",
        "url": "https://www.tenders.sa.gov.au/tender/SA-2025-006"
    },
    {
        "external_id": "SA-2025-007",
        "title": "Waste-to-Energy Feasibility Study and Technology Review",
        "description": "Engagement of a consultant to deliver a feasibility study for waste-to-energy solutions including anaerobic digestion and thermal treatment.",
        "agency": "Green Industries SA",
        "status": "open",
        "value_amount": 275000.00,
        "value_currency": "AUD",
        "published_date": "2025-05-08",
        "closing_date": "2025-06-22",
        "location": "South Australia",
        "category": "Clean Energy / Waste",
        "source": "mock",
        "url": "https://www.tenders.sa.gov.au/tender/SA-2025-007"
    },
    {
        "external_id": "SA-2025-008",
        "title": "Remote Telemetry and SCADA Modernisation Program",
        "description": "Replacement of legacy remote terminal units and upgrade of SCADA communications infrastructure for irrigation and water distribution networks.",
        "agency": "SA Water",
        "status": "open",
        "value_amount": 4100000.00,
        "value_currency": "AUD",
        "published_date": "2025-04-15",
        "closing_date": "2025-06-30",
        "location": "South Australia",
        "category": "Water / SCADA",
        "source": "mock",
        "url": "https://www.tenders.sa.gov.au/tender/SA-2025-008"
    },
    {
        "external_id": "SA-2025-009",
        "title": "Fleet Management SaaS Platform — 5 Year Licence",
        "description": "Procurement of a cloud-based fleet management platform including telematics, route optimisation and maintenance scheduling for 1,200 vehicles.",
        "agency": "Department of Treasury and Finance",
        "status": "awarded",
        "value_amount": 1200000.00,
        "value_currency": "AUD",
        "published_date": "2025-01-10",
        "closing_date": "2025-02-28",
        "location": "South Australia",
        "category": "Software / Fleet",
        "source": "mock",
        "url": "https://www.tenders.sa.gov.au/tender/SA-2025-009"
    },
    {
        "external_id": "SA-2025-010",
        "title": "Grid-Scale Battery Energy Storage System (BESS) — 100 MWh",
        "description": "Engineering, procurement and construction of a 100 MWh lithium-ion battery storage facility to provide frequency control ancillary services.",
        "agency": "ElectraNet",
        "status": "open",
        "value_amount": 85000000.00,
        "value_currency": "AUD",
        "published_date": "2025-05-12",
        "closing_date": "2025-09-30",
        "location": "South Australia",
        "category": "Energy Storage / BESS",
        "source": "mock",
        "url": "https://www.tenders.sa.gov.au/tender/SA-2025-010"
    }
]
